from ctypes import *
from pwndbg.dbg.dbgeng.wrapper.utils import ComMixin, IID


class IDebugControl(ComMixin, Structure):
    uuid = "5182e668-105e-416e-ad92-24ef800424ba"


class IDebugControlVtbl(Structure):
    _fields_ = [
        ("QueryInterface", WINFUNCTYPE(HRESULT, POINTER(IDebugControl), POINTER(IID), POINTER(c_void_p))),
        ("AddRef", c_void_p),
        ("Release", c_void_p),
        ("GetInterrupt", c_void_p),
        ("SetInterrupt", c_void_p),
        ("GetInterruptTimeout", c_void_p),
        ("SetInterruptTimeout", c_void_p),
        ("GetLogFile", c_void_p),
        ("OpenLogFile", c_void_p),
        ("CloseLogFile", c_void_p),
        ("GetLogMask", c_void_p),
        ("SetLogMask", c_void_p),
        ("Input", c_void_p),
        ("ReturnInput", c_void_p),
        ("Output", c_void_p),
        ("OutputVaList", c_void_p),
        ("ControlledOutput", c_void_p),
        ("ControlledOutputVaList", c_void_p),
        ("OutputPrompt", c_void_p),
        ("OutputPromptVaList", c_void_p),
        ("GetPromptText", c_void_p),
        ("OutputCurrentState", c_void_p),
        ("OutputVersionInformation", c_void_p),
        ("GetNotifyEventHandle", c_void_p),
        ("SetNotifyEventHandle", c_void_p),
        ("Assemble", c_void_p),
        ("Disassemble", c_void_p),
        ("GetDisassembleEffectiveOffset", c_void_p),
        ("OutputDisassembly", c_void_p),
        ("OutputDisassemblyLines", c_void_p),
        ("GetNearInstruction", c_void_p),
        ("GetStackTrace", c_void_p),
        ("GetReturnOffset", c_void_p),
        ("OutputStackTrace", c_void_p),
        ("GetDebuggeeType", c_void_p),
        ("GetActualProcessorType", c_void_p),
        ("GetExecutingProcessorType", c_void_p),
        ("GetNumberPossibleExecutingProcessorTypes", c_void_p),
        ("GetPossibleExecutingProcessorTypes", c_void_p),
        ("GetNumberProcessors", c_void_p),
        ("GetSystemVersion", c_void_p),
        ("GetPageSize", c_void_p),
        ("IsPointer64Bit", c_void_p),
        ("ReadBugCheckData", c_void_p),
        ("GetNumberSupportedProcessorTypes", c_void_p),
        ("GetSupportedProcessorTypes", c_void_p),
        ("GetProcessorTypeNames", c_void_p),
        ("GetEffectiveProcessorType", c_void_p),
        ("SetEffectiveProcessorType", c_void_p),
        ("GetExecutionStatus", c_void_p),
        ("SetExecutionStatus", c_void_p),
        ("GetCodeLevel", c_void_p),
        ("SetCodeLevel", c_void_p),
        ("GetEngineOptions", c_void_p),
        ("AddEngineOptions", c_void_p),
        ("RemoveEngineOptions", c_void_p),
        ("SetEngineOptions", c_void_p),
        ("GetSystemErrorControl", c_void_p),
        ("SetSystemErrorControl", c_void_p),
        ("GetTextMacro", c_void_p),
        ("SetTextMacro", c_void_p),
        ("GetRadix", c_void_p),
        ("SetRadix", c_void_p),
        ("Evaluate", c_void_p),
        ("CoerceValue", c_void_p),
        ("CoerceValues", c_void_p),
        ("Execute", c_void_p),
        ("ExecuteCommandFile", c_void_p),
        ("GetNumberBreakpoints", c_void_p),
        ("GetBreakpointByIndex", c_void_p),
        ("GetBreakpointById", c_void_p),
        ("GetBreakpointParameters", c_void_p),
        ("AddBreakpoint", c_void_p),
        ("RemoveBreakpoint", c_void_p),
        ("AddExtension", c_void_p),
        ("RemoveExtension", c_void_p),
        ("GetExtensionByPath", c_void_p),
        ("CallExtension", c_void_p),
        ("GetExtensionFunction", c_void_p),
        ("GetWindbgExtensionApis32", c_void_p),
        ("GetWindbgExtensionApis64", c_void_p),
        ("GetNumberEventFilters", c_void_p),
        ("GetEventFilterText", c_void_p),
        ("GetEventFilterCommand", c_void_p),
        ("SetEventFilterCommand", c_void_p),
        ("GetSpecificFilterParameters", c_void_p),
        ("SetSpecificFilterParameters", c_void_p),
        ("GetSpecificFilterArgument", c_void_p),
        ("SetSpecificFilterArgument", c_void_p),
        ("GetExceptionFilterParameters", c_void_p),
        ("SetExceptionFilterParameters", c_void_p),
        ("GetExceptionFilterSecondCommand", c_void_p),
        ("SetExceptionFilterSecondCommand", c_void_p),
        ("WaitForEvent", c_void_p),
        ("GetLastEventInformation", c_void_p),
    ]


IDebugControl._fields_ = [("lpVtbl", POINTER(IDebugControlVtbl))]
